version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - echo Install phase

  pre_build:
    commands:
      - echo Pre-build phase
      - echo fooo

  build:
    commands:
      - echo Build phase