# This is a basic workflow to help you get started with Actions

name: deploy

on:
  workflow_dispatch:

jobs:
  print:
    steps:
      - run: echo ${{ github.ref }}
  build:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install npm dependencies
        run: npm ci
      - name: Deploy prod
        run: SLS_DEBUG=* ./node_modules/.bin/sls deploy -v --stage dev --region us-east-2

